@startuml

title "Business: Create Order"

actor Business as B

participant "Business Dashboard" as App
participant Backend

B -> App: Opens the dashboard \n and navigates to \n create order page
B <-- App: Shows the create order page

B -> App: Enters order details \n and presses create button
App -> Backend: Post: Create order
Backend -> Backend: Validates order details

group If create order details valid
  App <-- Backend: 201 Created
  B <-- App: Shows order details
else else
  App <-- Backend: 401 Bad request
  B <-- App: Shows error
end

@enduml
