@startuml

class Bill {
  {field} + id: UUID
  + business_id: String
  + amount: float
  + paid: bool
  + create_datetime: datetime
  + update_datetime: datetime
  {method} + create_bill(): Bill
  + pay_bill(): bool
}

@enduml
