@startuml

title "Consumer Track Order"

actor Consumer as C

participant "Consumers's Mobile App" as App
participant "Backend Service" as Backend

C -> App: Opens the consumer's mobile app
App -> C: Shows the track order screen
C -> App: Enters the order tracking number
App -> Backend: Sends order tracking number
Backend -> Backend: Validates the order tracking number
Backend -> App: Sends the order details
App -> C: Shows the order details

@enduml
