@startuml

title "Driver: Sign-in"

actor Driver as D

participant "Drivers's Mobile App" as App
participant Backend

D -> App ++: Opens the driver's mobile app
D <-- App: Shows the sign in screen
D -> App: Enters their name, email, phone number and password
App -> Backend ++: Post: Sends sign in request
Backend -> Backend: Validates driver's credentials
group If driver details are valid
  App <-- Backend: 200 OK
  D <- Backend: Sends a one-time password
  D <-- App: Shows the OTP confirmation screen
else else
  App <-- Backend: 401 Unauthorized
  D <-- App: Shows the error message
end
D --> App: Enters the OTP
App -> Backend: Post: Validate driver's OTP
Backend -> Backend: Validates OTP
group If OTP is valid
  App <-- Backend: 200 OK: Sends driver details and access token
  D <-- App: Shows home page
else else
  App <-- Backend --: 401 Unauthorized
  D <-- App --: Shows the error message
end

@enduml
